### ISSUE TITLE
How to train

### ISSUE THREAD

**Issue by Govan111** [YaoZhongtian/YOLOv2-test-with-TensorFlow#1]
Hi, I read your code and feel it very good,but I want to train it by myself.Can you tell me how to train the model or provide the training code. == Thanks!

**Comment by zh0ngtian** [comment]
Sorry, my code cannot train the model. I downloaded the weights file from [here](https://pjreddie.com/media/files/yolo.weights) , and used this [tool](https://github.com/gliese581gg/YOLO_tensorflow/tree/master/YOLO_weight_extractor) to transform it.

**Comment by Govan111** [comment]
Thanks for repliying me！I’m setting about solving the problems of trainning based on your code.And I feel I can make it! Xie xie!
